### ISSUE TITLE
Recipe for Dark Iron Ingot doesn't exist

### ISSUE THREAD

**Issue by BowBoy1** [globalista-dev/Fabric-Reinforced-Obsidian#2] opened 2022-08-17 17:24 UTC
The crafting recipe for dark iron ingots doesn't seem to exist, you might wanna check that out.

**Comment by BowBoy1** [comment] 2022-08-17 17:28
btw i'm using this for 1.18.2, not sure how to backport if it's fixed in later versions

**Comment by globalista-dev** [comment] 2022-09-04 15:48
Closing this issue since I cannot reproduce it. There seems to be nothing wrong with the recipes.

![image](https://user-images.githubusercontent.com/35036442/188322127-7cf16e0b-25a4-4db4-8a27-c5abbc3f0c13.png)

![image](https://user-images.githubusercontent.com/35036442/188322089-87c4911e-3a45-48cb-8375-73a76b28488b.png)

**Closed as completed by globalista-dev** 2022-09-04 15:48 UTC
